"""Compile a theory's constructs and propositions to lavaan model syntax.

The output is deterministic. Constructs with measurement indicators become a latent
measurement model (=~), and directed propositions become structural paths (~).
"""
from __future__ import annotations

import re

from ._access import RELATION, enum, field, items, str_list, text

_PATH = {"causes", "increases", "decreases", "mediates"}
_NON_ALNUM = re.compile(r"[^a-z0-9]+")


def _san(s: str) -> str:
    """Sanitise a measurement label into a syntactic lavaan variable name."""
    s = _NON_ALNUM.sub("_", s.lower()).strip("_")
    return s or "x"


def compile_sem(T) -> str:
    T = T.data if hasattr(T, "data") else T
    out = [f"# lavaan model generated by theoryforge for {text(T.get('id'))}", "# Measurement model"]
    for c in items(T, "constructs"):
        meas = str_list(field(c, "measurement"))
        if meas:
            out.append(f"{text(field(c, 'id'))} =~ " + " + ".join(_san(m) for m in meas))
    out.append("# Structural model")
    for p in items(T, "propositions"):
        rel = enum(field(p, "relation"), RELATION)
        frm, to = text(field(p, "from")), text(field(p, "to"))
        if rel in _PATH:
            out.append(f"{to} ~ {frm}")
        elif rel == "associates":
            out.append(f"{frm} ~~ {to}")
        elif rel == "moderates":
            out.append(f"# moderation: {frm} moderates the path into {to} (specify interaction manually)")
    return "\n".join(out) + "\n"
