"""SEM/lavaan compilation (API_SPEC.md section 19): byte-identical to goldens.

The R suite (test-sem.R) asserts the same outputs, and checks with lavaan that
the zero block fixes exactly the covariances lavaan::sem() would free, that it
changes no other covariance and that the comments are read as comments.
"""
from pathlib import Path

import theoryforge as tf

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures"


# The comment lines compile_sem writes, built from the texts of API_SPEC.md
# section 19 so that each test below reads as the syntax it expects.
def header(theory_id):
    return [f"# lavaan model generated by theoryforge for {theory_id}",
            "# Written for lavaan::sem(); indicator names are the sanitised measurement "
            "entries and must match columns of the data."]


def single(*names):
    return ("# Single-indicator constructs (lavaan fixes the indicator's residual variance at "
            "zero, so each is treated as measured without error): " + ", ".join(names))


def loop(*names):
    return ("# Feedback loop among " + ", ".join(names) + ": a non-recursive model may not be "
            "identified. lavaan::sem() leaves these disturbances uncorrelated, and the order "
            "and rank conditions (Bollen, 1989) assume they may correlate, so check "
            "identification before fitting.")


def moderation(frm, to):
    return (f"# moderation: {frm} moderates the paths into {to}; add the product term by hand "
            f"({to} ~ <x>:{frm} for an observed predictor <x>; lavaan::sam() or the modsem "
            "package for latent variables)")


ZERO = ("# Covariances the theory fixes at zero (lavaan::sem() frees them by default; delete "
        "this block to restore its defaults)")
FREE = ("# Covariances with a moderator, left free (once a covariance names an observed "
        "exogenous variable, lavaan treats the variable as random and fixes at zero each of its "
        "covariances that the syntax does not write, including one with a product term added "
        "by hand)")


def text(*lines):
    out = []
    for line in lines:
        out += line if isinstance(line, list) else [line]
    return "\n".join(out) + "\n"


def sem_theory(constructs, propositions=(), theory_id="sem"):
    """A theory from (id, measurement) pairs and (from, relation, to) triples,
    the propositions numbered p1, p2 and so on in file order."""
    t = tf.new_theory(theory_id, "SEM")
    for cid, measurement in constructs:
        t.add_construct(cid, "Label", "A definition.", measurement=measurement)
    for i, (frm, rel, to) in enumerate(propositions, start=1):
        t.add_proposition(f"p{i}", frm, to, rel)
    return t


def bare(*ids):
    return [(c, None) for c in ids]


# -- the shipped theories ------------------------------------------------------

PANIC_MEASUREMENT = [
    "# Measurement model",
    "c_arousal =~ heart_rate_variability + self_reported_arousal",
    "c_perceived_threat =~ threat_appraisal_questionnaire",
    "c_avoidance =~ behavioural_avoidance_task + diary_counts",
    single("c_perceived_threat"),
    "# Structural model",
    "c_perceived_threat ~ c_arousal",
    "c_avoidance ~ c_perceived_threat",
    "c_arousal ~ c_perceived_threat",
]


def test_compile_sem_produces_the_exact_panic_lavaan_lines(panic_path):
    # Perceived threat has one indicator, and arousal and perceived threat form
    # a feedback loop that the syntax flags. No pair is both exogenous or both
    # terminal, so nothing is fixed at zero.
    assert tf.read(panic_path).compile_sem() == text(
        header("panic-network-2026"), PANIC_MEASUREMENT,
        loop("c_arousal", "c_perceived_threat"))
    v2 = tf.read(FIXTURES / "panic-network-2026-v2.theory.yaml")
    assert v2.compile_sem() == text(
        header("panic-network-2026-v2"), PANIC_MEASUREMENT, "c_avoidance ~ c_arousal",
        loop("c_arousal", "c_perceived_threat"))


def test_compile_sem_fixes_the_modality_switching_covariances_lavaan_would_free(modality_path):
    # Sensorimotor experience and lexical familiarity are both exogenous, and
    # switch cost and conceptual access both terminal. lavaan::sem() frees both
    # covariances by default, although the theory implies that each pair is
    # unrelated (the first pair is the fixture's own pred4).
    assert tf.read(modality_path).compile_sem() == (
        "# lavaan model generated by theoryforge for modality-switching-2026\n"
        "# Written for lavaan::sem(); indicator names are the sanitised measurement entries "
        "and must match columns of the data.\n"
        "# Measurement model\n"
        "c_sensorimotor_experience =~ modality_specific_perceptual_strength_ratings + "
        "sensory_experience_ratings + self_reported_frequency_of_first_hand_encounters\n"
        "c_modality_activation =~ bold_response_in_modality_specific_sensory_cortex + "
        "interference_from_a_concurrent_load_in_the_same_modality\n"
        "c_switch_cost =~ switch_minus_repeat_response_time_difference + "
        "switch_minus_repeat_error_rate_difference\n"
        "c_conceptual_access =~ semantic_categorisation_latency + lexical_decision_latency + "
        "accuracy_on_either_task\n"
        "c_lexical_familiarity =~ subjective_familiarity_ratings + "
        "corpus_frequency_of_the_word_form + age_of_acquisition\n"
        "# Structural model\n"
        "c_modality_activation ~ c_sensorimotor_experience\n"
        "c_switch_cost ~ c_modality_activation\n"
        "c_conceptual_access ~ c_modality_activation\n"
        "c_conceptual_access ~ c_lexical_familiarity\n"
        "# Covariances the theory fixes at zero (lavaan::sem() frees them by default; delete "
        "this block to restore its defaults)\n"
        "c_sensorimotor_experience ~~ 0*c_lexical_familiarity\n"
        "c_switch_cost ~~ 0*c_conceptual_access\n"
    )


def test_compile_sem_maps_an_associative_proposition_to_a_covariance(weak_path):
    # The weak theory's one association names no construct of a directed
    # relation, so the syntax has no causal graph to read.
    assert tf.read(weak_path).compile_sem() == text(
        header("weak-demo"), "# Measurement model", "# Structural model",
        "k_motivation ~~ k_drive")


def test_compile_sem_sanitises_labels_and_handles_every_relation_kind():
    t = tf.new_theory("san-demo", "Sanitise demo")
    t.add_construct("c1", "C1", "def", measurement=["Heart-Rate Variability!!", "  spaces  "])
    t.add_proposition("p_mod", "c1", "c2", "moderates")
    t.add_proposition("p_med", "c1", "c2", "mediates")
    # The mediation writes c2 ~ c1, so the moderation adds no second copy.
    assert t.compile_sem() == text(
        header("san-demo"), "# Measurement model", "c1 =~ heart_rate_variability + spaces",
        "# Structural model", moderation("c1", "c2"), "c2 ~ c1")


def test_compile_sem_is_byte_identical_to_the_golden_lavaan_files():
    for fixture in ("panic-network.theory.yaml", "panic-network-2026-v2.theory.yaml",
                    "modality-switching.theory.yaml", "weak-theory.theory.yaml"):
        t = tf.read(FIXTURES / fixture)
        golden = (FIXTURES / "expected" / f"{t.id}.sem.lavaan").read_bytes()
        assert t.compile_sem().encode("utf-8") == golden, fixture


# -- moderation ----------------------------------------------------------------

def test_a_moderator_gets_its_main_effect_written_once():
    # sem() reads an interaction only beside its main effects, and the theory's
    # moderator had no path to the outcome. The main effect comes before the
    # comment, unless a path relation anywhere in the file writes the same line.
    constructs = bare("threat", "ident", "perf")
    start = [header("sem"), "# Measurement model", "# Structural model"]
    t = sem_theory(constructs, [("threat", "decreases", "perf"), ("ident", "moderates", "perf")])
    assert t.compile_sem() == text(*start, "perf ~ threat", "perf ~ ident",
                                   moderation("ident", "perf"))
    t = sem_theory(constructs, [("ident", "moderates", "perf"), ("ident", "increases", "perf"),
                                ("threat", "decreases", "perf")])
    assert t.compile_sem() == text(*start, moderation("ident", "perf"), "perf ~ ident",
                                   "perf ~ threat")
    t = sem_theory(constructs, [("ident", "causes", "perf"), ("ident", "moderates", "perf")])
    assert t.compile_sem() == text(*start, "perf ~ ident", moderation("ident", "perf"))
    t = sem_theory(constructs, [("ident", "moderates", "perf"), ("ident", "moderates", "perf")])
    assert t.compile_sem() == text(*start, "perf ~ ident", moderation("ident", "perf"),
                                   moderation("ident", "perf"))


# -- covariances fixed at zero -------------------------------------------------

def test_the_zero_block_leaves_out_moderators_and_associated_pairs():
    # threat, prior and load are exogenous and perf and dropout terminal. The
    # moderator ident keeps lavaan's defaults, since a product term added by
    # hand changes its role, and prior and threat covary by the theory's own
    # word. All four are observed. lavaan takes the covariance of ident and load
    # from the data until threat ~~ 0*load names load, so the block writes it
    # free. The association already names prior and threat, whose covariances
    # with ident lavaan fixes at zero with or without the block.
    t = sem_theory(bare("threat", "ident", "prior", "load", "anxiety", "perf", "dropout"), [
        ("threat", "increases", "anxiety"),
        ("load", "increases", "anxiety"),
        ("anxiety", "decreases", "perf"),
        ("anxiety", "increases", "dropout"),
        ("prior", "increases", "perf"),
        ("ident", "moderates", "perf"),
        ("prior", "associates", "threat"),
    ])
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "# Structural model",
        "anxiety ~ threat", "anxiety ~ load", "perf ~ anxiety", "dropout ~ anxiety",
        "perf ~ prior", "perf ~ ident", moderation("ident", "perf"), "prior ~~ threat",
        ZERO, "threat ~~ 0*load", "prior ~~ 0*load", "perf ~~ 0*dropout",
        FREE, "ident ~~ load")


def test_an_observed_moderator_keeps_the_covariances_lavaan_takes_from_the_data():
    # lavaan::sem() takes the covariances of observed exogenous variables from
    # the data until a covariance line names one of them. It then treats that
    # variable as random and fixes at zero each of its covariances left
    # unwritten, so x1 ~~ 0*x2 alone would also fix those of the moderator m
    # with x1 and x2. The block writes them free.
    props = [("x1", "causes", "y"), ("x2", "causes", "y"), ("m", "moderates", "y")]
    structural = ["# Structural model", "y ~ x1", "y ~ x2", "y ~ m", moderation("m", "y")]
    t = sem_theory(bare("x1", "x2", "m", "y"), props)
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", structural,
        ZERO, "x1 ~~ 0*x2", FREE, "x1 ~~ m", "x2 ~~ m")
    # A line that restates a zero lavaan sets, between a latent and an observed
    # exogenous variable, names the observed one all the same.
    t = sem_theory([("x1", ["q1", "q2"]), ("x2", None), ("m", None), ("y", None)], props)
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "x1 =~ q1 + q2", structural,
        ZERO, "x1 ~~ 0*x2", FREE, "x2 ~~ m")
    # lavaan frees the covariances of a latent moderator itself and fixes at
    # zero those of a latent variable with an observed one, so a latent
    # moderator needs no line.
    t = sem_theory([("x1", None), ("x2", None), ("m", ["q1", "q2"]), ("y", None)], props)
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "m =~ q1 + q2", structural,
        ZERO, "x1 ~~ 0*x2")
    # Nor does an observed moderator when no zero line names an observed
    # exogenous variable, since lavaan then still takes its covariances from
    # the data.
    t = sem_theory([("f1", ["q1", "q2"]), ("f2", ["q3", "q4"]), ("m", None), ("y", None)], [
        ("f1", "causes", "y"), ("f2", "causes", "y"), ("m", "moderates", "y")])
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "f1 =~ q1 + q2", "f2 =~ q3 + q4",
        "# Structural model", "y ~ f1", "y ~ f2", "y ~ m", moderation("m", "y"),
        ZERO, "f1 ~~ 0*f2")


def test_the_zero_block_and_the_loop_caution_hold_in_a_cyclic_theory():
    # The rule encodes uncorrelated disturbances, which a feedback loop does
    # not change: x1 and x2 enter the loop and y1 and y2 leave it.
    t = sem_theory(bare("x1", "x2", "a", "b", "y1", "y2"), [
        ("x1", "causes", "a"), ("x2", "causes", "a"), ("a", "increases", "b"),
        ("b", "increases", "a"), ("b", "causes", "y1"), ("b", "causes", "y2"),
    ])
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "# Structural model",
        "a ~ x1", "a ~ x2", "b ~ a", "a ~ b", "y1 ~ b", "y2 ~ b",
        loop("a", "b"), ZERO, "x1 ~~ 0*x2", "y1 ~~ 0*y2")


def test_each_feedback_loop_gets_one_caution_in_the_order_of_its_first_member():
    # Members come in construct order, and a construct with an edge to itself
    # is a loop of one, as implications() reads it.
    t = sem_theory(bare("c", "a", "b", "d", "e"), [
        ("a", "causes", "b"), ("b", "causes", "a"), ("d", "causes", "d"),
        ("c", "causes", "e"), ("e", "causes", "c"), ("b", "causes", "d"),
    ])
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "# Structural model",
        "b ~ a", "a ~ b", "d ~ d", "e ~ c", "c ~ e", "d ~ b",
        loop("c", "e"), loop("a", "b"), loop("d"))


def test_undeclared_endpoints_follow_the_declared_constructs_in_the_zero_block():
    # validate() reports an endpoint that names no construct, and the syntax
    # writes it as an observed variable. The graph takes it in claim order,
    # after every declared construct, so y and z come before u and w. A
    # repeated id is one vertex.
    t = sem_theory(bare("y", "z", "y"), [("u", "causes", "y"), ("w", "causes", "z")])
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "# Structural model",
        "y ~ u", "z ~ w", ZERO, "y ~~ 0*z", "u ~~ 0*w")


# -- single indicators ---------------------------------------------------------

def test_single_indicator_constructs_are_listed_after_the_measurement_model():
    # One summary line lists them all (happy-vowel has seven).
    t = sem_theory([("a", ["q1"]), ("b", ["q2", "q3"]), ("c", ["q4"]), ("d", None)])
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "a =~ q1", "b =~ q2 + q3", "c =~ q4",
        single("a", "c"), "# Structural model")
    # lavaan reads the two lines of a repeated id as one factor with two
    # indicators, so it is no single-indicator construct.
    t = sem_theory([("a", ["q1"]), ("a", ["q2"])])
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "a =~ q1", "a =~ q2", "# Structural model")


def test_every_kind_of_line_in_one_theory():
    # The theory test-sem.R hands to lavaan: a single indicator (strain), a
    # moderation, a feedback loop (perf and strain) and a zero block.
    t = sem_theory([("threat", ["t1", "t2"]), ("load", ["l1", "l2"]), ("ident", ["i1", "i2"]),
                    ("perf", ["f1", "f2"]), ("strain", ["s1"]), ("absence", ["a1", "a2"]),
                    ("turnover", ["u1", "u2"])], [
        ("threat", "decreases", "perf"), ("load", "increases", "perf"),
        ("ident", "moderates", "perf"), ("perf", "causes", "strain"),
        ("strain", "causes", "perf"), ("strain", "increases", "absence"),
        ("strain", "increases", "turnover"),
    ])
    assert t.compile_sem() == text(
        header("sem"), "# Measurement model", "threat =~ t1 + t2", "load =~ l1 + l2",
        "ident =~ i1 + i2", "perf =~ f1 + f2", "strain =~ s1", "absence =~ a1 + a2",
        "turnover =~ u1 + u2", single("strain"), "# Structural model",
        "perf ~ threat", "perf ~ load", "perf ~ ident", moderation("ident", "perf"),
        "strain ~ perf", "perf ~ strain", "absence ~ strain", "turnover ~ strain",
        loop("perf", "strain"), ZERO, "threat ~~ 0*load", "absence ~~ 0*turnover")


def test_compile_sem_has_a_docstring():
    # api.md renders it, and it states what the syntax needs before a fit.
    doc = tf.compile_sem.__doc__
    assert doc is not None
    words = " ".join(doc.split())  # the wrapping of the lines is not the point
    for phrase in ("lavaan::sem()", "column", "single indicator", "identif", "dummy"):
        assert phrase in words, phrase
