import theoryforge as tf


def test_compile_sem(panic_path):
    lav = tf.read(panic_path).compile_sem()
    assert "# lavaan model generated by theoryforge for panic-network-2026" in lav
    # measurement model: sanitized indicator names
    assert "c_arousal =~ heart_rate_variability + self_reported_arousal" in lav
    assert "c_perceived_threat =~ threat_appraisal_questionnaire" in lav
    # structural model: directed paths (to ~ from)
    assert "c_perceived_threat ~ c_arousal" in lav
    assert "c_arousal ~ c_perceived_threat" in lav
    assert lav.endswith("\n")


def test_compile_sem_associative(weak_path):
    lav = tf.read(weak_path).compile_sem()
    # weak-demo proposition q1 is associative -> covariance
    assert "k_motivation ~~ k_drive" in lav


def test_dossier(panic_path):
    d = tf.read(panic_path).dossier()
    assert d.startswith("# theoryforge dossier: Network theory of panic disorder")
    assert "- Aggregate rigor score: 84.8/100" in d
    assert "| item | status | score | weight |" in d
    assert "| falsifiability | pass | 1.0 | 0.15 |" in d
    assert "## Preregistration" in d
    assert "# Preregistration: Network theory of panic disorder" in d
