# SEM/lavaan compilation (API_SPEC.md section 19): byte-identical to goldens.

test_that("tf_compile_sem produces the exact panic lavaan lines", {
  theory <- tf_read(tf_fixture_path("panic-network.theory.yaml"))
  expected <- paste0(paste(c(
    "# lavaan model generated by theoryforge for panic-network-2026",
    "# Measurement model",
    "c_arousal =~ heart_rate_variability + self_reported_arousal",
    "c_perceived_threat =~ threat_appraisal_questionnaire",
    "c_avoidance =~ behavioural_avoidance_task + diary_counts",
    "# Structural model",
    "c_perceived_threat ~ c_arousal",
    "c_avoidance ~ c_perceived_threat",
    "c_arousal ~ c_perceived_threat"
  ), collapse = "\n"), "\n")
  expect_identical(tf_compile_sem(theory), expected)
})

test_that("tf_compile_sem maps an associative proposition to a covariance", {
  weak <- tf_read(tf_fixture_path("weak-theory.theory.yaml"))
  out <- tf_compile_sem(weak)
  expect_true(grepl("k_motivation ~~ k_drive", out, fixed = TRUE))
})

test_that("tf_compile_sem sanitises labels and handles every relation kind", {
  theory <- tf_theory("san-demo", "Sanitise demo") |>
    tf_add_construct("c1", "C1", "def",
                     measurement = c("Heart-Rate Variability!!", "  spaces  ")) |>
    tf_add_proposition("p_mod", "c1", "c2", "moderates") |>
    tf_add_proposition("p_med", "c1", "c2", "mediates")
  out <- tf_compile_sem(theory)
  expect_true(grepl("c1 =~ heart_rate_variability + spaces", out, fixed = TRUE))
  expect_true(grepl(
    "# moderation: c1 moderates the path into c2 (specify interaction manually)",
    out, fixed = TRUE))
  expect_true(grepl("c2 ~ c1", out, fixed = TRUE))
})

test_that("tf_compile_sem output ends with a single trailing newline (LF)", {
  theory <- tf_read(tf_fixture_path("panic-network.theory.yaml"))
  out <- tf_compile_sem(theory)
  expect_false(grepl("\r", out, fixed = TRUE))
  expect_true(endsWith(out, "\n"))
  expect_false(endsWith(out, "\n\n"))
})

test_that("tf_compile_sem is byte-identical to the golden lavaan files", {
  cases <- list(
    list(fixture = "panic-network.theory.yaml", id = "panic-network-2026"),
    list(fixture = "panic-network-2026-v2.theory.yaml", id = "panic-network-2026-v2"),
    list(fixture = "weak-theory.theory.yaml", id = "weak-demo")
  )
  for (cs in cases) {
    theory <- tf_read(tf_fixture_path(cs$fixture))
    got <- tf_compile_sem(theory)
    golden <- tf_read_golden(tf_expected_path(paste0(cs$id, ".sem.lavaan")))
    expect_identical(got, golden, info = cs$id)
  }
})
