# SEM/lavaan compilation (API_SPEC.md section 19): byte-identical to goldens.
# test_sem.py asserts the same outputs in Python, and the lavaan checks at the
# end are R's alone.

# The comment lines tf_compile_sem() writes, built from the texts of API_SPEC.md
# section 19 so that each test below reads as the syntax it expects.
.sem_header <- function(id) {
  c(paste0("# lavaan model generated by theoryforge for ", id),
    paste0("# Written for lavaan::sem(); indicator names are the sanitised measurement ",
           "entries and must match columns of the data."))
}
.sem_single <- function(...) {
  paste0("# Single-indicator constructs (lavaan fixes the indicator's residual variance at ",
         "zero, so each is treated as measured without error): ", paste(c(...), collapse = ", "))
}
.sem_loop <- function(...) {
  paste0("# Feedback loop among ", paste(c(...), collapse = ", "), ": a non-recursive model ",
         "may not be identified. lavaan::sem() leaves these disturbances uncorrelated, and the ",
         "order and rank conditions (Bollen, 1989) assume they may correlate, so check ",
         "identification before fitting.")
}
.sem_moderation <- function(from, to) {
  paste0("# moderation: ", from, " moderates the paths into ", to, "; add the product term ",
         "by hand (", to, " ~ <x>:", from, " for an observed predictor <x>; lavaan::sam() or ",
         "the modsem package for latent variables)")
}
.SEM_ZERO <- paste0("# Covariances the theory fixes at zero (lavaan::sem() frees them by ",
                    "default; delete this block to restore its defaults)")
.SEM_FREE <- paste0("# Covariances with a moderator, left free (once a covariance names an ",
                    "observed exogenous variable, lavaan treats the variable as random and ",
                    "fixes at zero each of its covariances that the syntax does not write, ",
                    "including one with a product term added by hand)")
.sem_text <- function(...) paste0(paste(c(...), collapse = "\n"), "\n")

# A theory from list(id, measurement) and list(from, relation, to) entries,
# the propositions numbered p1, p2 and so on in file order.
.sem_theory <- function(constructs, propositions = list(), id = "sem") {
  theory <- tf_theory(id, "SEM")
  for (con in constructs) {
    theory <- tf_add_construct(theory, con[[1L]], "Label", "A definition.",
                               measurement = con[[2L]])
  }
  for (i in seq_along(propositions)) {
    p <- propositions[[i]]
    theory <- tf_add_proposition(theory, paste0("p", i), p[[1L]], p[[3L]], p[[2L]])
  }
  theory
}
.bare <- function(...) lapply(c(...), function(x) list(x, NULL))

# -- the shipped theories -------------------------------------------------------

.panic_measurement <- c(
  "# Measurement model",
  "c_arousal =~ heart_rate_variability + self_reported_arousal",
  "c_perceived_threat =~ threat_appraisal_questionnaire",
  "c_avoidance =~ behavioural_avoidance_task + diary_counts",
  .sem_single("c_perceived_threat"),
  "# Structural model",
  "c_perceived_threat ~ c_arousal",
  "c_avoidance ~ c_perceived_threat",
  "c_arousal ~ c_perceived_threat")

test_that("tf_compile_sem produces the exact panic lavaan lines", {
  # Perceived threat has one indicator, and arousal and perceived threat form
  # a feedback loop that the syntax flags. No pair is both exogenous or both
  # terminal, so nothing is fixed at zero.
  theory <- tf_read(tf_fixture_path("panic-network.theory.yaml"))
  expect_identical(tf_compile_sem(theory), .sem_text(
    .sem_header("panic-network-2026"),
    .panic_measurement,
    .sem_loop("c_arousal", "c_perceived_threat")))
  v2 <- tf_read(tf_fixture_path("panic-network-2026-v2.theory.yaml"))
  expect_identical(tf_compile_sem(v2), .sem_text(
    .sem_header("panic-network-2026-v2"),
    .panic_measurement,
    "c_avoidance ~ c_arousal",
    .sem_loop("c_arousal", "c_perceived_threat")))
})

test_that("tf_compile_sem fixes the modality-switching covariances lavaan would free", {
  # Sensorimotor experience and lexical familiarity are both exogenous, and
  # switch cost and conceptual access both terminal. lavaan::sem() frees both
  # covariances by default, although the theory implies that each pair is
  # unrelated (the first pair is the fixture's own pred4).
  theory <- tf_read(tf_fixture_path("modality-switching.theory.yaml"))
  expect_identical(tf_compile_sem(theory), .sem_text(
    "# lavaan model generated by theoryforge for modality-switching-2026",
    paste0("# Written for lavaan::sem(); indicator names are the sanitised measurement ",
           "entries and must match columns of the data."),
    "# Measurement model",
    paste0("c_sensorimotor_experience =~ modality_specific_perceptual_strength_ratings + ",
           "sensory_experience_ratings + self_reported_frequency_of_first_hand_encounters"),
    paste0("c_modality_activation =~ bold_response_in_modality_specific_sensory_cortex + ",
           "interference_from_a_concurrent_load_in_the_same_modality"),
    paste0("c_switch_cost =~ switch_minus_repeat_response_time_difference + ",
           "switch_minus_repeat_error_rate_difference"),
    paste0("c_conceptual_access =~ semantic_categorisation_latency + lexical_decision_latency + ",
           "accuracy_on_either_task"),
    paste0("c_lexical_familiarity =~ subjective_familiarity_ratings + ",
           "corpus_frequency_of_the_word_form + age_of_acquisition"),
    "# Structural model",
    "c_modality_activation ~ c_sensorimotor_experience",
    "c_switch_cost ~ c_modality_activation",
    "c_conceptual_access ~ c_modality_activation",
    "c_conceptual_access ~ c_lexical_familiarity",
    paste0("# Covariances the theory fixes at zero (lavaan::sem() frees them by default; ",
           "delete this block to restore its defaults)"),
    "c_sensorimotor_experience ~~ 0*c_lexical_familiarity",
    "c_switch_cost ~~ 0*c_conceptual_access"))
})

test_that("tf_compile_sem maps an associative proposition to a covariance", {
  # The weak theory's one association names no construct of a directed
  # relation, so the syntax has no causal graph to read.
  weak <- tf_read(tf_fixture_path("weak-theory.theory.yaml"))
  expect_identical(tf_compile_sem(weak), .sem_text(
    .sem_header("weak-demo"), "# Measurement model", "# Structural model",
    "k_motivation ~~ k_drive"))
})

test_that("tf_compile_sem sanitises labels and handles every relation kind", {
  theory <- tf_theory("san-demo", "Sanitise demo") |>
    tf_add_construct("c1", "C1", "def",
                     measurement = c("Heart-Rate Variability!!", "  spaces  ")) |>
    tf_add_proposition("p_mod", "c1", "c2", "moderates") |>
    tf_add_proposition("p_med", "c1", "c2", "mediates")
  # The mediation writes c2 ~ c1, so the moderation adds no second copy.
  expect_identical(tf_compile_sem(theory), .sem_text(
    .sem_header("san-demo"),
    "# Measurement model",
    "c1 =~ heart_rate_variability + spaces",
    "# Structural model",
    .sem_moderation("c1", "c2"),
    "c2 ~ c1"))
})

test_that("tf_compile_sem output ends with a single trailing newline (LF)", {
  theory <- tf_read(tf_fixture_path("panic-network.theory.yaml"))
  out <- tf_compile_sem(theory)
  expect_false(grepl("\r", out, fixed = TRUE))
  expect_true(endsWith(out, "\n"))
  expect_false(endsWith(out, "\n\n"))
})

test_that("tf_compile_sem is byte-identical to the golden lavaan files", {
  cases <- list(
    list(fixture = "panic-network.theory.yaml", id = "panic-network-2026"),
    list(fixture = "panic-network-2026-v2.theory.yaml", id = "panic-network-2026-v2"),
    list(fixture = "modality-switching.theory.yaml", id = "modality-switching-2026"),
    list(fixture = "weak-theory.theory.yaml", id = "weak-demo")
  )
  for (cs in cases) {
    theory <- tf_read(tf_fixture_path(cs$fixture))
    got <- tf_compile_sem(theory)
    golden <- tf_read_golden(tf_expected_path(paste0(cs$id, ".sem.lavaan")))
    expect_identical(got, golden, info = cs$id)
  }
})

# -- moderation -----------------------------------------------------------------

test_that("a moderator gets its main effect, written once", {
  # sem() reads an interaction only beside its main effects, and the theory's
  # moderator had no path to the outcome. The main effect comes before the
  # comment, unless a path relation anywhere in the file writes the same line.
  constructs <- .bare("threat", "ident", "perf")
  expect_identical(
    tf_compile_sem(.sem_theory(constructs, list(c("threat", "decreases", "perf"),
                                                c("ident", "moderates", "perf")))),
    .sem_text(.sem_header("sem"), "# Measurement model", "# Structural model",
              "perf ~ threat", "perf ~ ident", .sem_moderation("ident", "perf")))
  expect_identical(
    tf_compile_sem(.sem_theory(constructs, list(c("ident", "moderates", "perf"),
                                                c("ident", "increases", "perf"),
                                                c("threat", "decreases", "perf")))),
    .sem_text(.sem_header("sem"), "# Measurement model", "# Structural model",
              .sem_moderation("ident", "perf"), "perf ~ ident", "perf ~ threat"))
  expect_identical(
    tf_compile_sem(.sem_theory(constructs, list(c("ident", "causes", "perf"),
                                                c("ident", "moderates", "perf")))),
    .sem_text(.sem_header("sem"), "# Measurement model", "# Structural model",
              "perf ~ ident", .sem_moderation("ident", "perf")))
  expect_identical(
    tf_compile_sem(.sem_theory(constructs, list(c("ident", "moderates", "perf"),
                                                c("ident", "moderates", "perf")))),
    .sem_text(.sem_header("sem"), "# Measurement model", "# Structural model",
              "perf ~ ident", .sem_moderation("ident", "perf"),
              .sem_moderation("ident", "perf")))
})

# -- covariances fixed at zero --------------------------------------------------

test_that("the zero block leaves out moderators and associated pairs", {
  # threat, prior and load are exogenous and perf and dropout terminal. The
  # moderator ident keeps lavaan's defaults, since a product term added by hand
  # changes its role, and prior and threat covary by the theory's own word. All
  # four are observed. lavaan takes the covariance of ident and load from the
  # data until threat ~~ 0*load names load, so the block writes it free. The
  # association already names prior and threat, whose covariances with ident
  # lavaan fixes at zero with or without the block.
  theory <- .sem_theory(.bare("threat", "ident", "prior", "load", "anxiety", "perf", "dropout"),
                        list(c("threat", "increases", "anxiety"),
                             c("load", "increases", "anxiety"),
                             c("anxiety", "decreases", "perf"),
                             c("anxiety", "increases", "dropout"),
                             c("prior", "increases", "perf"),
                             c("ident", "moderates", "perf"),
                             c("prior", "associates", "threat")))
  expect_identical(tf_compile_sem(theory), .sem_text(
    .sem_header("sem"), "# Measurement model", "# Structural model",
    "anxiety ~ threat", "anxiety ~ load", "perf ~ anxiety", "dropout ~ anxiety",
    "perf ~ prior", "perf ~ ident", .sem_moderation("ident", "perf"), "prior ~~ threat",
    .SEM_ZERO, "threat ~~ 0*load", "prior ~~ 0*load", "perf ~~ 0*dropout",
    .SEM_FREE, "ident ~~ load"))
})

# The theories of the next two tests share their propositions. Every construct
# is observed in the first, x1 is latent in the second and the moderator m is
# latent in the third.
.moderated_theories <- function() {
  props <- list(c("x1", "causes", "y"), c("x2", "causes", "y"), c("m", "moderates", "y"))
  list(
    observed = .sem_theory(.bare("x1", "x2", "m", "y"), props),
    restating = .sem_theory(list(list("x1", c("q1", "q2")), list("x2", NULL), list("m", NULL),
                                 list("y", NULL)), props),
    latent = .sem_theory(list(list("x1", NULL), list("x2", NULL), list("m", c("q1", "q2")),
                              list("y", NULL)), props))
}

test_that("an observed moderator keeps the covariances lavaan takes from the data", {
  # lavaan::sem() takes the covariances of observed exogenous variables from the
  # data until a covariance line names one of them. It then treats that variable
  # as random and fixes at zero each of its covariances left unwritten, so
  # x1 ~~ 0*x2 alone would also fix those of the moderator m with x1 and x2. The
  # block writes them free.
  theories <- .moderated_theories()
  structural <- c("# Structural model", "y ~ x1", "y ~ x2", "y ~ m",
                  .sem_moderation("m", "y"))
  expect_identical(tf_compile_sem(theories$observed), .sem_text(
    .sem_header("sem"), "# Measurement model", structural,
    .SEM_ZERO, "x1 ~~ 0*x2", .SEM_FREE, "x1 ~~ m", "x2 ~~ m"))
  # A line that restates a zero lavaan sets, between a latent and an observed
  # exogenous variable, names the observed one all the same.
  expect_identical(tf_compile_sem(theories$restating), .sem_text(
    .sem_header("sem"), "# Measurement model", "x1 =~ q1 + q2", structural,
    .SEM_ZERO, "x1 ~~ 0*x2", .SEM_FREE, "x2 ~~ m"))
  # lavaan frees the covariances of a latent moderator itself and fixes at zero
  # those of a latent variable with an observed one, so a latent moderator needs
  # no line.
  expect_identical(tf_compile_sem(theories$latent), .sem_text(
    .sem_header("sem"), "# Measurement model", "m =~ q1 + q2", structural,
    .SEM_ZERO, "x1 ~~ 0*x2"))
  # Nor does an observed moderator when no zero line names an observed exogenous
  # variable, since lavaan then still takes its covariances from the data.
  theory <- .sem_theory(list(list("f1", c("q1", "q2")), list("f2", c("q3", "q4")),
                             list("m", NULL), list("y", NULL)),
                        list(c("f1", "causes", "y"), c("f2", "causes", "y"),
                             c("m", "moderates", "y")))
  expect_identical(tf_compile_sem(theory), .sem_text(
    .sem_header("sem"), "# Measurement model", "f1 =~ q1 + q2", "f2 =~ q3 + q4",
    "# Structural model", "y ~ f1", "y ~ f2", "y ~ m", .sem_moderation("m", "y"),
    .SEM_ZERO, "f1 ~~ 0*f2"))
})

test_that("the zero block and the loop caution hold in a cyclic theory", {
  # The rule encodes uncorrelated disturbances, which a feedback loop does not
  # change: x1 and x2 enter the loop and y1 and y2 leave it.
  theory <- .sem_theory(.bare("x1", "x2", "a", "b", "y1", "y2"),
                        list(c("x1", "causes", "a"), c("x2", "causes", "a"),
                             c("a", "increases", "b"), c("b", "increases", "a"),
                             c("b", "causes", "y1"), c("b", "causes", "y2")))
  expect_identical(tf_compile_sem(theory), .sem_text(
    .sem_header("sem"), "# Measurement model", "# Structural model",
    "a ~ x1", "a ~ x2", "b ~ a", "a ~ b", "y1 ~ b", "y2 ~ b",
    .sem_loop("a", "b"), .SEM_ZERO, "x1 ~~ 0*x2", "y1 ~~ 0*y2"))
})

test_that("each feedback loop gets one caution, in the order of its first member", {
  # Members come in construct order, and a construct with an edge to itself is
  # a loop of one, as tf_implications() reads it.
  theory <- .sem_theory(.bare("c", "a", "b", "d", "e"),
                        list(c("a", "causes", "b"), c("b", "causes", "a"),
                             c("d", "causes", "d"), c("c", "causes", "e"),
                             c("e", "causes", "c"), c("b", "causes", "d")))
  expect_identical(tf_compile_sem(theory), .sem_text(
    .sem_header("sem"), "# Measurement model", "# Structural model",
    "b ~ a", "a ~ b", "d ~ d", "e ~ c", "c ~ e", "d ~ b",
    .sem_loop("c", "e"), .sem_loop("a", "b"), .sem_loop("d")))
})

test_that("undeclared endpoints follow the declared constructs in the zero block", {
  # tf_validate() reports an endpoint that names no construct, and the syntax
  # writes it as an observed variable. The graph takes it in claim order, after
  # every declared construct, so y and z come before u and w. A repeated id is
  # one vertex.
  theory <- .sem_theory(.bare("y", "z", "y"),
                        list(c("u", "causes", "y"), c("w", "causes", "z")))
  expect_identical(tf_compile_sem(theory), .sem_text(
    .sem_header("sem"), "# Measurement model", "# Structural model",
    "y ~ u", "z ~ w", .SEM_ZERO, "y ~~ 0*z", "u ~~ 0*w"))
})

# -- single indicators ----------------------------------------------------------

test_that("single-indicator constructs are listed after the measurement model", {
  # One summary line lists them all (happy-vowel has seven).
  theory <- .sem_theory(list(list("a", "q1"), list("b", c("q2", "q3")), list("c", "q4"),
                             list("d", NULL)))
  expect_identical(tf_compile_sem(theory), .sem_text(
    .sem_header("sem"), "# Measurement model", "a =~ q1", "b =~ q2 + q3", "c =~ q4",
    .sem_single("a", "c"), "# Structural model"))
  # lavaan reads the two lines of a repeated id as one factor with two
  # indicators, so it is no single-indicator construct.
  theory <- .sem_theory(list(list("a", "q1"), list("a", "q2")))
  expect_identical(tf_compile_sem(theory), .sem_text(
    .sem_header("sem"), "# Measurement model", "a =~ q1", "a =~ q2", "# Structural model"))
})

# -- lavaan ---------------------------------------------------------------------

# The parameter table lavaan::sem() would build, with the options it sets by
# default, so that no data are needed. Its default estimator, maximum
# likelihood, takes the observed exogenous variables as given (fixed.x = TRUE),
# where lavaanify() alone would not. lavaanify() then warns when a covariance
# line names such a variable, which sem() does not.
.sem_table <- function(syntax) {
  lavaan::lavaanify(syntax, auto = TRUE, model.type = "sem", int.ov.free = TRUE,
                    int.lv.free = FALSE, auto.fix.first = TRUE, auto.fix.single = TRUE,
                    auto.var = TRUE, auto.cov.lv.x = TRUE, auto.cov.y = TRUE,
                    auto.th = TRUE, auto.delta = TRUE, auto.efa = TRUE, fixed.x = TRUE,
                    warn = FALSE)
}

test_that("lavaan frees exactly the covariances the block fixes, two degrees of freedom", {
  skip_if_not_installed("lavaan")
  syntax <- tf_compile_sem(tf_read(tf_fixture_path("modality-switching.theory.yaml")))
  lines <- strsplit(syntax, "\n", fixed = TRUE)[[1L]]
  start <- match(.SEM_ZERO, lines)
  expect_false(is.na(start))
  without <- .sem_text(lines[seq_len(start - 1L)])
  # sprintf() returns no string for no rows, where paste() would return " ~~ ".
  free_covariances <- function(pt) {
    keep <- pt$op == "~~" & pt$lhs != pt$rhs & pt$free > 0L
    sprintf("%s ~~ %s", pt$lhs[keep], pt$rhs[keep])
  }
  pt_without <- .sem_table(without)
  pt_with <- .sem_table(syntax)
  expect_identical(free_covariances(pt_without),
                   c("c_sensorimotor_experience ~~ c_lexical_familiarity",
                     "c_switch_cost ~~ c_conceptual_access"))
  expect_identical(free_covariances(pt_with), character(0))
  # Both models hold the same observed variables, so the degrees of freedom
  # differ by the number of parameters the block fixes.
  expect_identical(lavaan::lavNames(pt_with, "ov"), lavaan::lavNames(pt_without, "ov"))
  expect_identical(sum(pt_without$free > 0L) - sum(pt_with$free > 0L), 2L)
})

test_that("the block changes no covariance but those its zero lines fix", {
  # Each pair of constructs is open, a free parameter or a covariance taken
  # from the data, or closed, fixed at zero. Cutting the block off restores
  # lavaan's defaults, and against them the block may close only the pairs its
  # zero lines name. An observed moderator's covariances stay open, as the
  # free lines keep them.
  skip_if_not_installed("lavaan")
  # sprintf() returns no string for no pairs, where ifelse() would return a
  # logical vector.
  key <- function(a, b) sprintf("%s %s", pmin(a, b), pmax(a, b))
  open_pairs <- function(pt) {
    keep <- pt$op == "~~" & pt$lhs != pt$rhs & (pt$free > 0L | pt$exo == 1L)
    sort(key(pt$lhs[keep], pt$rhs[keep]))
  }
  expected <- list(observed = c("m x1", "m x2", "x1 x2"), restating = c("m x2"),
                   latent = c("x1 x2"))
  for (name in names(expected)) {
    syntax <- tf_compile_sem(.moderated_theories()[[name]])
    lines <- strsplit(syntax, "\n", fixed = TRUE)[[1L]]
    start <- match(.SEM_ZERO, lines)
    without <- .sem_text(lines[seq_len(start - 1L)])
    expect_identical(open_pairs(.sem_table(without)), expected[[name]], info = name)
    zero <- grep(" ~~ 0\\*", lines, value = TRUE)
    named <- vapply(strsplit(sub(" ~~ 0\\*", " ", zero), " ", fixed = TRUE),
                    function(p) key(p[[1L]], p[[2L]]), character(1))
    expect_identical(open_pairs(.sem_table(syntax)), setdiff(expected[[name]], named),
                     info = name)
  }
})

test_that("lavaan reads the cautions as comments and the block as covariances", {
  # Every kind of line the syntax writes is here: a single indicator (strain), a
  # moderation, a feedback loop (perf and strain) and a zero block. The comments
  # hold semicolons, which lavaan also reads as line breaks, so a parser that
  # split lines before dropping comments would take the text after them as
  # model syntax.
  theory <- .sem_theory(list(list("threat", c("t1", "t2")), list("load", c("l1", "l2")),
                             list("ident", c("i1", "i2")), list("perf", c("f1", "f2")),
                             list("strain", "s1"), list("absence", c("a1", "a2")),
                             list("turnover", c("u1", "u2"))),
                        list(c("threat", "decreases", "perf"), c("load", "increases", "perf"),
                             c("ident", "moderates", "perf"), c("perf", "causes", "strain"),
                             c("strain", "causes", "perf"), c("strain", "increases", "absence"),
                             c("strain", "increases", "turnover")))
  syntax <- tf_compile_sem(theory)
  expect_identical(syntax, .sem_text(
    .sem_header("sem"), "# Measurement model", "threat =~ t1 + t2", "load =~ l1 + l2",
    "ident =~ i1 + i2", "perf =~ f1 + f2", "strain =~ s1", "absence =~ a1 + a2",
    "turnover =~ u1 + u2", .sem_single("strain"), "# Structural model",
    "perf ~ threat", "perf ~ load", "perf ~ ident", .sem_moderation("ident", "perf"),
    "strain ~ perf", "perf ~ strain", "absence ~ strain", "turnover ~ strain",
    .sem_loop("perf", "strain"), .SEM_ZERO, "threat ~~ 0*load", "absence ~~ 0*turnover"))
  skip_if_not_installed("lavaan")
  pt <- NULL
  expect_no_warning(pt <- lavaan::lavaanify(syntax))
  user <- pt[pt$user == 1L & pt$op != "=~", ]
  expect_identical(paste(user$lhs, user$op, user$rhs),
                   c("perf ~ threat", "perf ~ load", "perf ~ ident", "strain ~ perf",
                     "perf ~ strain", "absence ~ strain", "turnover ~ strain",
                     "threat ~~ load", "absence ~~ turnover"))
  fixed <- user$op == "~~"
  expect_identical(user$free[fixed], c(0L, 0L))
  expect_identical(user$ustart[fixed], c(0, 0))
})
